version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: techx-mysql-db
    restart: always
    environment:
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ROOT_PASSWORD: '${DB_ROOT_PASSWORD}'
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  backend:
      build: ./backend
      container_name: techx-backend
      restart: on-failure
      ports:
        - "3000:3000"
      volumes:
        - ./backend:/usr/src/app
        - /usr/src/app/node_modules
      environment:
        - DB_HOST=db
        - DB_PORT=${DB_PORT}
        - DB_USERNAME=${DB_USERNAME}
        - DB_PASSWORD=${DB_PASSWORD}
        - DB_DATABASE=${DB_DATABASE}
        - JWT_SECRET=${JWT_SECRET}
      depends_on:
        - db

  frontend:
      build: ./frontend
      container_name: techx-frontend
      ports:
        - "4200:4200"
      volumes:
        - ./frontend:/usr/src/app
        - /usr/src/app/node_modules
      depends_on:
        - backend

volumes:
  mysql-data: